language: node_js
node_js:
  - 7

before_install:
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"

before_script:
  - lerna bootstrap

script:
  - npm test
  # symlink CHANGELOG.md primer-css/CHANGELOG.md
  - ln -s CHANGELOG.md modules/primer-css

after_success:
  - script/after_success

deploy:
  # publish release candidates on release branches
  - provider: script
    script: script/release-candidate
    skip_cleanup: true
    on:
      branch: release*

  # publish "final" releases on master
  - provider: script
    script: script/release
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    secure: W9lPRuuPMNwElkXZ8UZtu5phgUNleDCK0PgERa28dkh5b0Y9xzRpIQPRJfqVYAPtnMVXhfYcqryMzA4oj0E4fc7OxQsKmMeF1OcTuj5N4CM5xXR/qXDehOUTp6fpCToIX9d4hZ2H///PCExpul3TcfxYJe6EWQCHYd1n6zKRl8g=
