language: node_js
node_js:
  - 7

before_script:
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"
  - npm whoami
  - echo lerna bootstrap

script:
  - echo npm test

after_success:
  - echo script/cibuild --yes
