language: node_js
node_js:
  - 7

before_install:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - git log -3
  - exit 1

before_script:
  - lerna bootstrap

script:
  - npm test

after_success:
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"
  - script/cibuild --yes
