language: node_js
node_js:
  - 7

before_script:
  - echo "TRAVIS_COMMIT: ${TRAVIS_COMMIT}"
  - echo "TRAVIS_PULL_REQUEST_SHA: ${TRAVIS_PULL_REQUEST_SHA}"
  - exit 1
  - lerna bootstrap

script:
  - npm test

after_success:
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"
  - script/cibuild --yes
