language: node_js
node_js:
  - 7

before_script:
  - lerna bootstrap

script:
  - npm test

after_success:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}" > .npmrc
  - script/cibuild --yes
