language: node_js
node_js:
  - 7

before_script:
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"
  - npm whoami
  - lerna bootstrap

script:
  - npm test

after_success:
  - script/cibuild --yes
