language: node_js
node_js:
  - 7

before_install:
  - echo "commit: $TRAVIS_COMMIT"
  - echo "pr SHA: $TRAVIS_PULL_REQUEST_SHA"
  - exit 1

before_script:
  - lerna bootstrap

script:
  - npm test

after_success:
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"
  - script/cibuild --yes
