language: node_js
node_js:
  - 7

env:
  global:
    - secure: fsY9o/wT4lfo7nUTNe772p2+A8UmUNe6gq1NFVtX0+GHUNXQg2pAtQqWLTwOisylGlSaTYF1eO5TwBlcaiujzQj5IULmJARFM3ELPGDmXIy0o2Bl9iVk/97NsVHvFApiwsKk4PQhDZw6bRJPNqVGw8d5bEuCslv0W6ZpvPz/jpk=

before_install:
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"

before_script:
  - lerna bootstrap

script:
  - npm test

after_success:
  - script/after_success

deploy:
  # publish release candidates on release branches
  - provider: sript
    script: script/release-candidate
    on:
      branch: /^release/

  # publish "final" releases on master
  - provider: script
    script: script/release
    on:
      branch: master

notifications:
  slack:
    secure: W9lPRuuPMNwElkXZ8UZtu5phgUNleDCK0PgERa28dkh5b0Y9xzRpIQPRJfqVYAPtnMVXhfYcqryMzA4oj0E4fc7OxQsKmMeF1OcTuj5N4CM5xXR/qXDehOUTp6fpCToIX9d4hZ2H///PCExpul3TcfxYJe6EWQCHYd1n6zKRl8g=
