name: Bundle report
on:
  pull_request_target:
    paths:
      - 'src/**'
      - '.github/workflows/bundle_report.yml'
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn
      - run: yarn dist
      - name: Reporting bundle sizes
        run: script/bundle-size-report.js --all

      - name: Reporting selector diffs
        run: script/selector-diff-report
