name: Bundle stats
on: [pull_request]
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - run: yarn pretest
      - name: Reporting bundle sizes
        uses: primer/comment-token-update@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment-token: 'bundle_table'
          script: |
            echo "<pre>"
            script/bundle-size-report.js
            echo "</pre>"

      - name: Reporting selector diffs
        uses: primer/comment-token-update@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment-token: 'diff_report'
          script: |
            diff=$(script/selector-diff-report)
            if [[ $diff ]]; then
              echo "### Selectors added/removed"
              echo "```diff"
              echo $diff
              echo "```"
            fi
