name: CI
on: [push]
jobs:
  lint_css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
          with:
            node-version: 12
      - run: yarn
      - name: Lint CSS with Stylelint
        run: yarn stylelint
      - name: Look for unused stylelint:disable lines
        run: yarn stylelint -- --report-needless-disables

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
          with:
            node-version: 12
      - run: yarn
      - run: yarn dist
      - name: Testing code
        run: yarn test
