name: CI
on: [push]
jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn
      - name: Lint source files
        run: yarn stylelint
      - name: Look for unused stylelint:disable lines
        run: yarn stylelint -- --report-needless-disables

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn
      - name: Lint workflow files
        run: yarn eslint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn
      - run: yarn dist
      - name: Testing code
        run: yarn test
