name: Release
on:
  push:
    branches:
      - 'main'
      - '!dependabot/**'
jobs:
  release:
    if: ${{ github.repository == 'primer/css' }}

    name: Final
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn
      - run: |
          git config --global user.name 'GitHub Design Systems Bot'
          git config --global user.email 'primer-css@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_AUTH_TOKEN_SHARED }}

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          title: Release Tracking
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_AUTH_TOKEN_SHARED }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
